시발 깃허브 이건 수정 못하나
딱히 바꾼건 없고 설명 수정안되서 그냥 띄어쓰기 한번 하고 글씀
NullReferenceException: Object reference not set to an instance of an
object
scRunner.OnTriggerEnter (UnityEngine.Collider coll) (at
Assets/Script/scRunner.cs:43)
오류 메시지 이거임 ㅇㅇ