Sound이벤트 관련 스크립트
NullReferenceException: Object reference not set to an
오류가 떠서 일단 싱크 해봄
오류 내용은
instance of an object
scRunner.OnTriggerEnter (UnityEngine.Collider
coll) (at Assets/Script/scRunner.cs:43)

생성 관점에 따라서 문제가 생기는거 같은데
감을 못잡겠음 ㅠㅠ
스크립트와 스크립트 사이 생성 호출 문제인건가